[package]
name = "from_as_file"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"

[dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
serde_yaml = "0.8.14"
toml = "0.5"
