[package]
name = "from_as"
version = "0.1.0"
authors = ["sreeise"]
edition = "2018"

[workspace]
members = [
  "derive_from_as",
  "from_as_file"
]

[dependencies]
serde = "1.0.88"
serde_json = "1.0.38"
serde_yaml = "0.8.9"
serde_derive = "1.0.88"
toml = "0.5"
derive_from_as = { path = "./derive_from_as" }
from_as_file = { path = "./from_as_file" }
